---
- name: add GPG key into apt
  apt_key:
    url=https://packagecloud.io/gpg.key
    state=present

- name: add grafana repository
  apt_repository:
    repo="deb https://packagecloud.io/grafana/stable/debian/ jessie main"
    state=present

- name: install grafana
  apt:
    pkg=grafana
    update_cache=true

- name: start grafana
  service:
    name=grafana-server
    state=started
    enabled=yes

